baseURL = "https://mobiledads.live/"
languageCode = "en-us"
title = "@MobileDads Social Networks!"
theme = "slate"
publishDir = "docs"

[ params ]
BackgroundStyle = "#657383;"
Favicon = "favicon.ico"
OpenLinksInNewWindow = true
